menu_rails:
  client:
    menu_items:
      - home:
          text: Home
          url:  :root_path
          authorization:
            can:        :read
            class_name: PagesController
      - contact:
          text: Contact
          url:  "http://www.myrandomurl.com/"
          authorization:
            class_name: MissingCanKey
          active:
            # It's ignored because url is a string
            controller_only: true
      - about:
          text: About
          url:  :about_path
      - dummy1:
          text: Dummy1
          url:  :dummy1_path
          active:
            method: :always_inactive
      - not_visible:
          text: Not visible
          url:  :root_path
          authorization:
            can:        :read
            class_name: NotVisibleController
  admin:
    menu_items:
      - home:
          text: Home
          url:  :root_path

  custom_class_menu:
    class_name: SecondDummyMenu
    menu_items:
      - home:
          class_name: SecondDummyMenuItem
          text:       Home
          url:        :root_path