menu_rails:
  client:
    menu_items:
      - home:
          text: Home
          url:  :root_path
          authorization:
            can:        :read
            class_name: PagesController
      - contact:
          text: Contact
          url:  "http://www.myrandomurl.com/"
          authorization:
            class_name: MissingCanKey
          active:
            # Don't care
            controller_only: true
      - about:
          text: About
          url:  :about_path
      - dummy1:
          text: Dummy1
          url:  :dummy1_path
          active:
            method: :always_inactive
      - not_visible:
          text: Not visible
          url:  :root_path
          authorization:
            can:        :read
            class_name: NotVisibleController
  admin:
    menu_items:
      - home:
          text: Home
          url:  :root_path
  # app_config:
  # client:
  #   menu:
  #     - text:       Home
  #       class_name: 'PagesController'
  #       can:        :read
  #       url:        :root_path
  #     - text:       About
  #       class_name: 'PagesController'
  #       can:        :read
  #       url:        :root_path
  #     - text:       Archives
  #       class_name: 'PagesController'
  #       can:        :read
  #       url:        :root_path
  #     - text:       Dropdown
  #       class_name: 'PagesController'
  #       can:        :read
  #       url:        :root_path
  #     - text:       Templates
  #       class_name: 'PagesController'
  #       can:        :read
  #       url:        :root_path
  #     - text:       Contact
  #       class_name: 'PagesController'
  #       can:        :read
  #       url:        :root_path
  #       last:       true
  # admin:
  #   menu:
  #     - text:       Home
  #       class_name: 'Admin::PagesController'
  #       can:        :read